class A{
    public void xyz() throws ArithmeticException{
        int a=19/0;
        System.out.println(a);
    }
}
public class Thr3 {
    public static void main(String[] args){
        A obj= new A();
        try{
            obj.xyz();
        }
        catch(ArithmeticException e){
            System.out.println("It has been handled");
        }
    }
}
